### ISSUE TITLE
Remove unnecessary binaries - causing client not to start

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/cncnet-yr-client-package#261]
Reported by Lud0wig

> Turns out that the answer to my question is nothing. Nothing happens with the old binaries, you can have any file in any of these > directories and it won't get deleted

> Some people have really old installations (late 2020 kind of old) and at one point there was an Rampastring.Tools.dll assembly in Resources\Binaries\Windows which is unused (the client loads Rampastring.Tools.dll from Resources\Binaries instead). The problem is that this assembly never gets updated 

> If these people with old installations tried to run the client via dotnet .\Resources\Binaries\Windows\clientdx.dll after they updated to 9.0, it will fail with the following error:
```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'Rampastring.Tools, Version=2.0.4.0, Culture=neutral, PublicKeyToken=null'. Could not find or load a specific file. (0x80131621)
File name: 'Rampastring.Tools, Version=2.0.4.0, Culture=neutral, PublicKeyToken=null'
 ---> System.IO.FileLoadException: Could not load file or assembly 'Rampastring.Tools, Version=2.0.4.0, Culture=neutral, PublicKeyToken=null'.
   at System.Runtime.Loader.AssemblyLoadContext.<LoadFromPath>g____PInvoke|5_0(IntPtr ptrNativeAssemblyBinder, UInt16* ilPath, UInt16* niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at DTAClient.Program.DefaultAssemblyLoadContextOnResolving(AssemblyLoadContext assemblyLoadContext, AssemblyName assemblyName) in D:\a\xna-cncnet-client\xna-cncnet-client\DXMainClient\Program.cs:line 129
   at System.Runtime.Loader.AssemblyLoadContext.GetFirstResolvedAssemblyFromResolvingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at DTAClient.PreStartup.Initialize(StartupParams parameters)
   at DTAClient.Program.Main(String[] args) in D:\a\xna-cncnet-client\xna-cncnet-client\DXMainClient\Program.cs:line 111
 ```
 
> That's why if they double click  CnCNetYRLauncher.exe it doesn't run
> And fixing this is as simple as deleting Rampastring.Tools.dll from Resources\Binaries\Windows
> This will allow the DirectX client to run and finish the update

**Task:**  
Compare of 8.32 to 9.0 and see what binaries need to be added to the updater (delete files section)

**Comment by GrantBartlett** [comment]
![image](https://user-images.githubusercontent.com/6104940/230890721-2ba951c1-d49e-4492-bca1-0ae6bc968461.png)

Seems now this fails because of deleting the old bianary. 
https://discord.com/channels/188156159620939776/1075737402028589136/1094910987884298260

**Comment by devo1929** [comment]
@GrantBartlett I believe we should be ok on this now for the net7 stuff.
